### ISSUE TITLE
리뷰 기능 :: score 컬럼에 저장 될 수 있는 점수 범위 제한 문제

### ISSUE THREAD

**Issue by JIHYE0705** [AndrewDongminYoo/52market.shop#12]
**관련 문제/이슈**  
- 현재 Review Entity 내에 score에 대한 범위가 없습니다 이것에 대해 서버쪽에서 미리 점수의 ranage를 걸어두면 어떨까요?

**추가하고자 하는 기능에 대한 간략한 설명**  
- @Min, @Max 어노테이션을 이용하여 점수의 제한을 둔다

**고민하고 있는 내용에 대한 설명 (말로 설명할 수 있어야 코드가 나옵니다.)**  
- 점수의 범위를 1 ~ 5 라고 했을때 서버쪽에서 먼저 제한을 걸어두면 나중에 처리할때 편하지 않을까 생각이듭니다
ex) @Min(1) @Max(5)

**부가적인 설명 / 목표치**

**Comment by AndrewDongminYoo** [comment]
이 부분을 계속해서 사용자에 대한 리뷰의 평균치로 갱신해야 하는데, int 값 자체보다는 int의 집합이 더 좋을 것 같다는 생각은 드네요.

**Comment by JIHYE0705** [comment]
그렇다면 review score는 list로 두고 user score는 그 점수들의 평균값으로 하려면 연관관계가 추가되어야겠네욤 🤔

**Comment by AndrewDongminYoo** [comment]
이거 하나 하려고 모델을 하나 더 만들어야 하기는 좀 복잡한 것 같고, 리뷰가 작성될 때 해당 유저의 모든 리뷰들의 스코어를 조회해서 평균값을 업데이트 해주는 식으로 하면 될 것 같네요!
